showNewVersionIcon: true
hideAfterStartup: true
randomControllerPort: true
runTimeFormat: "hh : mm : ss"
trayOrders:
  - - icon
  - - status
    - traffic
    - text
hideTrayIcon: false
profileParsersText: |-
  parsers: # array
    - reg: https://.*$
      file: "/Users/zhongyuming/.config/clash/parser.js"
proxyOrder: 0
silentUpdate: true
theme: 0
systemTheme: true
trayProxiesStyle: 0
useSystemEmoji: false
showNotifications: false
connShowProcess: true
showTrayProxyDelayIndicator: true
bypassText: |
  bypass:
    - "*.icloud.developer.apple.com"
    - "*.mxdm8.com"
    - "*.cdn.apple-cloudkit.com"
    - 127.0.0.1
    - 192.168.0.0/16
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 100.64.0.0/10
    - 17.0.0.0/8
    - localhost
    - "*.local"
    - 169.254.0.0/16
    - 224.0.0.0/4
    - 240.0.0.0/4
trayScriptManualRunTime: 1681287900420
